name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.16', '1.13' ]
      # fail-fast: false

    name: Go ${{ matrix.go }} sample
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v .

    - name: Test cmd with root
      run: sudo go test ./drivers/...

    - name: Test
      run: go test ./...
